Adjective1=input("enter a Adjective")
Noun1=input("enter a Noun")
Animal1=input("enter a Animal")
Verb1=input("enter a Verb")
Adjective2=input("enter a Adjective")
Adjective3=input("enter a Adjective")
PluralNoun1=input("enter a Plural Noun")
Food1=input("enter a Food")
Verb2=input("enter a Verb")
Noun2=input("enter a Noun")
BodyPart1=input("enter a Body")
Adjective4=input("enter a Adjective")
Food2=input("enter a Food")
Liquid1=input("enter a Liquid")
Sound1=input("enter a Sound")
verb3=input("enter a Verb")
adverb4=input("enter a Adverb")
noun3=input("enter a Noun")
noun4=input("enter a Noun")
adverb5=input("enter a Adverb")
print("today I went to the",Adjective1,"")
print("zoo with my favorite",Noun1,"")
print("First,we saw a giant",Animal1,"")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
