x=input("do you have any experience")
print(x)
input("tell me about yourself")
print(x)
input("what is your biggest weakness")
print(x)
input("where do you see yourself in five years")
print(x)
input("why do you want this job")
print(x)